package main

var usermap = map[string]string{
    "trooble" : "TheTrooble",
    "thetrooble" : "TheTrooble",
    "cakebombs" : "Cake",
    "cake" : "Cake",
    "cake_" : "Cake",
    "cakebombs" : "Cake",
    "alec" : "AlecK47",
    "aleck" : "AlecK47",
    "aleck47" : "AlecK47",
    "amajesticbarrel" : "AMajesticBarrel",
    "barrel" : "AMajesticBarrel",
    "ferret" : "FearfulFerret",
    "fearfulferret" : "FearfulFerret",
    "your name" : "your name here",
    "kirkq" : "Kirkq",
    "zach" : "Zach",
    "zachsk" : "Zach",
    "squall" : "Squall",
    "matty" : "Matty",
    "mattyice" : "Matty",
    "mattyice3131" : "Matty",
    "churchnsarge" : "ChurchnSarge",
    "church" : "ChurchnSarge",
    "ed" : "Ed",
    "progamingwithed" : "Ed",
    "hannah" : "Muffins",
    "muffins" : "Muffins",
    "noclip" : "noclip",
    "spike" : "Spike",
    "spikevegeta" : "Spike",
    "redshoedude" : "redshoedude",
    "redshoe" : "redshoedude",
    "sent" : "Sent",
    "laplacier" : "Laplacier",
    "oblivion" : "Oblivion",
}